# Generated by Django 5.2.1 on 2025-06-05 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('users', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHasRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_role', models.ForeignKey(db_column='id_role', help_text='Role associated with the user', on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='roles.role')),
                ('id_user', models.ForeignKey(db_column='id_user', help_text='User associated with the role', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.user')),
            ],
            options={
                'verbose_name': 'User Role Association',
                'verbose_name_plural': 'User Role Associations',
                'db_table': 'users_has_roles',
                'ordering': ['id_user', 'id_role'],
                'unique_together': {('id_user', 'id_role')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(help_text='Roles assigned to the user', related_name='users', through='users.UserHasRoles', to='roles.role'),
        ),
    ]
